package trycatchp;

public class program2 {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
		int a=45;
		int b=0;
		
		try
		{
			int c=a/b;
			System.out.println(c);
		}
		
			catch (ArithmeticException e) {
				System.out.println("from 2nd block");
			}
		catch (Exception e) {
			System.out.println("from 3rd block");
		}
		    finally {
		    	System.out.println("Byee");
		    }
		}

	}


